name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout

      - name: Setup Node
        uses: actions/setup-node

      - name: Install dependencies
        uses: bahmutov/npm-install

      - name: Build project
        run: npm install -g vite && vite build --base=https://johnchughes.github.io/yoto-image-drawing/

      - name: Upload production-ready build files
        uses: actions/upload-artifact
        with:
          name: production-files
          path: ./dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: production-files
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist